language: python
notifications:
  slack: pdx-capstone-team-d:cXdI5uhxszX12tSNdERuUKky

install: "pip install -r requirements.txt"

script: 
  - python ./services/S3Service/TestS3Service.py
  - python ./services/XMLConverterService/TestXMLConverterService.py
  - python TestSchedulerController.py
  # - python ./services/LiveService/testLiveService.py
  - coverage run SchedulerController.py
after_success: coveralls